export const ADD_FACTURE = "ADD_FACTURE";
export const INIT_FACTURE = "INIT_FACTURE";
export const SET_SELECTED_FACTURE = "SET_SELECTED_FACTURE";
export const SET_SELECT_FACTURE_BY_SEARCH_NAME =
  "SET_SELECT_FACTURE_BY_SEARCH_NAME";
export const SET_BEFORE_SET_SELECTED_FACTURE =
  "SET_BEFORE_SET_SELECTED_FACTURE";
