export const INIT_TRAVAU = "INIT_TRAVAU";
export const ADD_TRAVAU = "ADD_TRAVAU";
export const SET_SELECTED_TRAVAU = "SET_SELECTED_TRAVAU";
export const UPDATE_TRAVAU = "UPDATE_TRAVAU";
export const UPDATE_TRAVAU_FACT = "UPDATE_TRAVAU_FACT";
export const SET_SELECT_TRAVAU_BY_SEARCH_NAME =
  "SET_SELECT_TRAVAU_BY_SEARCH_NAME";
